### ISSUE TITLE
add display:block

### ISSUE THREAD

**Issue by Cyloon** [CarmelaPippa/fed-the-fundamentals#2]
https://github.com/CarmelaPippa/fed-the-fundamentals/blob/92fb44dda4f697c0e85c860923ec074080c6012a/css/style.css#L436C7-L436C7

Hello! Sorry for my previous post, I was totally locating the wrong place in the code.
Here! add display:block and it should make the whole square/button clickable.

**Comment by CarmelaPippa** [comment]
I understood the problem. It was padding and not a display block but thank you so much, now it works better.
